language: node_js  # 设置语言
node_js: stable    # 设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install -g gitbook@3.2.3
#    - npm install -g gitbook-cli@2.3.2

install:
    - gitbook install   # 安装插件

branches:
    only:
        - save  # 只监测save分支，可根据自己情况设置

env:
    global:
        - GH_REF: github.com/jokerbj/book.git  #设置GH_REF	

script:
    - gitbook init
    - gitbook build
    - bash deploy.sh
